"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/Whale.py']

# Extra items to add to dist/HelloAppStore.app/Contents/Resources
DATA_FILES = [
    'Resources/whale.ini',
    'Resources/online.png',
    'Resources/offline.png',
]

OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'Resources/AppIcon.icns',
    'plist': 'src/Info.plist',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'requests']
)
